name: compile

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pi-base/compile@v0.0.0
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: README
        path: README.md
